# Generated by Django 2.2 on 2019-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontroller',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
    ]
