# Generated by Django 2.2 on 2019-05-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190504_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontroller',
            name='key',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscontroller',
            name='original',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesscontroller',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
