# Generated by Django 2.2 on 2019-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190513_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontroller',
            name='key',
            field=models.CharField(max_length=2048),
        ),
    ]
