# Generated by Django 2.2 on 2019-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20190513_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontroller',
            name='key',
            field=models.FileField(upload_to='files/'),
        ),
    ]
